### ISSUE TITLE
definir banco de dados

### ISSUE THREAD

**Issue by cleysonsilvame** [lucasvitalmelo/todo-app#5]

**Comment by cleysonsilvame** [comment]
Faremos o uso do banco de dados relacional

**Comment by cleysonsilvame** [comment]
![todo-app-database-v1](https://user-images.githubusercontent.com/62582404/156290180-995cc2b1-cae7-4f8c-bf42-97def116a261.png)

**Comment by lucasvitalmelo** [comment]
Será usado o banco de dados MySQL e implementações com ORM
